language: elixir
elixir:
- 1.7
otp_release:
- 21.0
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
- mix deps.get
env:
- MIX_ENV=test
script:
- mix credo --strict
- mix test
notifications:
  email: false
deploy:
  provider: heroku
  app: activity-namer
  run: POOL_SIZE=2 mix ecto.migrate
  api_key:
    secure: Uwb23EjauqDV71Y2jIM2ghA8tjrBsTUUBDCmMb2NqJysy3xDaYMGguMwRMwLGYkgBJ5m4Cwj8oal7axci3LeQiQtHnHe7Kyb91RhdMzKg9M3P6ARXbezaKYwCTLHM5r8mK2x92apxYbsmJxy/65f8MiLHjGiR4Tz5NllXVUQMgSh2pgvxgNmlxYCzGsqg/yDA4TAK8QMQDWVppybeRMa2WyoNPKWmCc2MaqMnUk6vET81KnLA8VZyxJag+HNoSz0GSMdQUHimXN1uDayqdqj7gt9iNUtUM0nlmyQrrR9kbrP7ihyUvW8xc8M1uigg0loWY3nnPEFEjJtmoe7kpPmIQi7ie3snd10VqzutnXatvBTbJQTj/RbK5bnw/v0B0B6O+ckqgD0VwpJA1eYw20LywhNDyuqoIvoELSvQe/jHFmokrMAnjifEEqbY32OxFWo6wRG3GN1g7rqxMJZsC9pTSW+otBu6C7gAASCHfhRdIxTcegAgOUG/Hb2uM4QEfGX8kIW/BkrntdUIxqxjE9Q/38NmfD6SPuHUc7gM0kUvp9/w2Gw8d9CAmssgKvV+Pq6Z/oeHY2IoZoa4R2RxUG8gXtYGFos6fYMk3bOd2QMKnI5NwoEp8bbnpwHlnEQht+N5bkF4wQ2uKv5xP94RXpI62CuUIe6Iec7HlE7no4WH1E=
